### ISSUE TITLE
Missing AngularGraphPairData

### ISSUE THREAD

**Issue by mmartirossyan** [Materials-Informatics-Laboratory/SODAS#2]
Hi, 

It looks like the graphite (https://github.com/LLNL/graphite) code that SODAS runs on was updated recently and the AngularGraphPairData module is no longer there. I was able to have things work with installing an older version of graphite, but I just wanted to notify you that currently the two software are not compatible in their most recent commits.

**Comment by Materials-Informatics-Laboratory** [comment]
Thanks for letting us know. We'll have it updated shortly.

**Comment by Materials-Informatics-Laboratory** [comment]
Integrated graphite with sodas to avoid future conflicts
